//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunFavori
    {
        public int FavoriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string IpNumarası { get; set; }
    
        public virtual tblUrunler tblUrunler { get; set; }
        public virtual tblUyeler tblUyeler { get; set; }
    }
}
